Language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - curl https://us-central1-sirbogapps.cloudfunctions.net/stop
  - curl https://us-central1-sirbogapps.cloudfunctions.net/start
